sudo: required

language: cpp
cache: ccache

addons:
  apt:
    update: true
  homebrew:
    packages:
    - ninja
    - ccache

matrix:
  include:
    - name: "Linux build using gcc"
      os: linux
      compiler: gcc
    - name: "Linux build using clang"
      os: linux
      compiler: clang
    - name: "osx build"
      os: osx
      compiler: clang
    # osx links gcc to clang; so skip

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get -y -q --no-install-recommends install
        zlib1g-dev libncursesw5-dev libgeoip-dev
        nettle-dev libgmp-dev libcurl4-gnutls-dev libsdl2-dev
        libogg-dev libvorbis-dev libopusfile-dev libtheora-dev
        libwebp-dev libjpeg8-dev libpng-dev
        libfreetype6-dev libglew-dev libopenal-dev
        liblua5.2-dev ninja-build;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      touch BrewFile;
      echo 'brew "ccache"' >> BrewFile;
      echo 'brew "ninja"' >> BrewFile;
      brew bundle;
    fi
  - |
    # workarounds to make ccache work
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "clang++" ]; then
      sudo ln -s $(which ccache) /usr/lib/ccache/clang
      sudo ln -s $(which ccache) /usr/lib/ccache/clang++
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
    fi

before_script:
  - ccache --zero-stats
  # In older versions of gcc the missing field initializer warning fires even when the initialization list is empty, which is stupid.
  # This issue is fixed in version 5 of gcc, so if we get a newer version on Travis the warning can be re-enabled.
  - if [ "$CC" == "gcc" ]; then export CXXFLAGS="$CXXFLAGS -Wno-missing-field-initializers"; fi
  - export CXXFLAGS="$CXXFLAGS -D__extern_always_inline=inline"

script:
  - cmake -DUSE_PRECOMPILED_HEADER=0
    -DUSE_WERROR=1 -DBE_VERBOSE=1 -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DUSE_DEBUG_OPTIMIZE=0
    -H. -Bbuild
  - cmake --build build -- -j8

before_cache:
  - ccache --show-stats

notifications:
  irc:
    - "irc.freenode.org#daemon-engine"
  on_success: change
  on_failure: always

branches:
  except:
    - debian
